parameters:
    # Adds a fallback DATABASE_URL if the env var is not set.
    # This allows you to run cache:warmup even if your
    # environment variables are not available yet.
    # You should not need to change this value.
    env(DATABASE_URL): ''

doctrine:
    dbal:
        # configure these for your database server
        #driver: 'pdo_mysql'
        #host: 'docker_cron_mysql'
        #port: '3306'
        #dbname: 'btoweb'
        #user: 'btoweb'
        #password: '4mdqgDAPW2igW7p8'
        #charset: UTF8
        driver: '%env(DATABASE_DRIVER)%'
        url: '%env(DATABASE_URL)%'
    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
