#index:
#    path: /
#    defaults: { _controller: 'App\Controller\DefaultController::index' }
JMSJobQueueBundle:
    resource: "@JMSJobQueueBundle/Controller/"
    type: annotation
    prefix: /jobs

AppBundle:
    resource: "../src/Controller/"
    type: annotation
    prefix: /admin